// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNr5ET2P7PDZR8ZamZrglaWVHjDibcy74',
    appId: '1:593899405417:web:5b13be3ed1f8b73d4b22f8',
    messagingSenderId: '593899405417',
    projectId: 'library-management-syste-a37b3',
    authDomain: 'library-management-syste-a37b3.firebaseapp.com',
    storageBucket: 'library-management-syste-a37b3.firebasestorage.app',
    measurementId: 'G-TCSNTJGPJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRRz26HVnVbOVN9ZPe_fW6szGGH780Oa0',
    appId: '1:593899405417:android:56a764af2f4eaa054b22f8',
    messagingSenderId: '593899405417',
    projectId: 'library-management-syste-a37b3',
    storageBucket: 'library-management-syste-a37b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAg82nFS5u_BzQWSVI2NE0-Fa2BMoPCmU',
    appId: '1:593899405417:ios:e34b2ec090a5855f4b22f8',
    messagingSenderId: '593899405417',
    projectId: 'library-management-syste-a37b3',
    storageBucket: 'library-management-syste-a37b3.firebasestorage.app',
    iosClientId: '593899405417-nc33iu7au698huah8dl059b5sqh7uibt.apps.googleusercontent.com',
    iosBundleId: 'com.example.problemsheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAg82nFS5u_BzQWSVI2NE0-Fa2BMoPCmU',
    appId: '1:593899405417:ios:e34b2ec090a5855f4b22f8',
    messagingSenderId: '593899405417',
    projectId: 'library-management-syste-a37b3',
    storageBucket: 'library-management-syste-a37b3.firebasestorage.app',
    iosClientId: '593899405417-nc33iu7au698huah8dl059b5sqh7uibt.apps.googleusercontent.com',
    iosBundleId: 'com.example.problemsheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNr5ET2P7PDZR8ZamZrglaWVHjDibcy74',
    appId: '1:593899405417:web:fcc45198fe95f8ca4b22f8',
    messagingSenderId: '593899405417',
    projectId: 'library-management-syste-a37b3',
    authDomain: 'library-management-syste-a37b3.firebaseapp.com',
    storageBucket: 'library-management-syste-a37b3.firebasestorage.app',
    measurementId: 'G-H1X0K64SXZ',
  );
}
